services:
  - type: web
    name: quality-management-system
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 80
    healthCheckPath: /
    # 仅部署前端应用，无需持久化存储或额外构建命令
    autoDeploy: true