services:
  # 前端服务配置
  - type: web
    name: qms-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://qms-backend.onrender.com
  
  # 后端服务配置
  - type: web
    name: qms-backend
    env: docker
    dockerfilePath: ./docker/Dockerfile.render
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080