services:
  # 前端服务 - 完全免费
  - type: static_site
    name: qms-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/build
    # 配置路由重写，支持SPA应用
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    envVars:
      - key: REACT_APP_USE_MOCK_DATA
        value: "true"

  # 后端服务（使用Docker）
  # 注意：这也使用免费计划，但不活跃15分钟后会休眠
  - type: web
    name: qms-backend
    env: docker
    region: singapore  # 亚洲区域，通常访问更快
    plan: free  # 使用免费计划
    dockerfilePath: docker/Dockerfile.render
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "10000"