services:
  # 前端服务配置
  - type: web
    name: qms-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    # 配置在端口3000上运行
    envVars:
      - key: PORT
        value: "3000"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"

  # 后端服务配置
  - type: web
    name: qms-backend
    env: docker
    region: singapore  # 亚洲区域，访问更快
    plan: free  # 使用免费计划
    dockerfilePath: docker/Dockerfile.render
    dockerContext: .
    healthCheckPath: /health
    # 配置在端口3001上运行
    envVars:
      - key: PORT
        value: "3001"