services:
  - type: web
    name: quality-management-system
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 80
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    # 可选：添加持久化存储
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    # 使用预编译的后端可执行文件的配置
    buildCommand: echo "Skipping build - using precompiled executable"
    startCommand: ./startup.sh