version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: qms-backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - qms-network
    volumes:
      - backend-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: qms-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - qms-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  qms-network:
    driver: bridge

volumes:
  backend-data:
    driver: local