version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: quality-management-backend
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
      - quality-management-network
    volumes:
      - backend-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: quality-management-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - quality-management-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  quality-management-network:
    driver: bridge

volumes:
  backend-data:
    driver: local